name: .NET Core CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: ExplorandoMarte.sln    # Nome da solução
      Test_Project_Path: ExplorandoMarte.Tests/ExplorandoMarte.Tests.csproj  # Caminho para o projeto de testes 
      Wap_Project_Directory: ExplorandoMarte  # Defina o diretório do projeto WAP
      Wap_Project_Path: ExplorandoMarte/ExplorandoMarte.csproj  # Defina o caminho do projeto WAP

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Run tests
      run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }} --no-restore --verbosity normal
